name: tests

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage

      - name: Run tests
        run: |
          python -m pytest -q

      - name: Generate coverage report
        run: |
          python -m coverage run -m pytest -q
          python -m coverage html

      - name: Upload coverage HTML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
